language: cpp
os: linux
dist: Bionic
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../Lab10
  - make -j
  - ./test/MP2_TESTS
notifications:
  email: false